### PR TITLE
[Work in Progress] Add IPFS Driver

### PR DESCRIPTION
**Pull request by kantai**
Enable an IPFS driver, using IPNS

Building off work from @dsdjolence

### CODE REVIEW

**Comment by meteorplus** [comment]
Hey @kantai is this ready to use?

**Comment by FIREFOXCYBER** [comment]
Any progress yet?

**Comment by x5engine** [comment]
i think so...

**Comment by criadoperez** [comment]
@fritzsima and @bjorger , you can take a look at this work on the ipfs driver.

**Comment by criadoperez** [comment]
Closing this PR as latest IPFS Driver work is now on PR #427 , expected to be completed by @fritzsima and @bjorger in the next couple of days.

**Pull request closed without merging**
